# Generated by Django 4.2.3 on 2024-04-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_parking_num_spaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='priority',
            field=models.BooleanField(default=False),
        ),
    ]
